apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: task2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: task2-static
  volumeName: task2-pv
