apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: task4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web
        image: hashicorp/http-echo:0.2.3
        args: ["-text=Hello from webapp", "-listen=:8080"]
        ports:
        - containerPort: 8080
