apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: task4
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8008  
      nodePort: 30080
